[package]
name = "fastsplit"
version = "0.1.0"
edition = "2021"

[lib]
name = "fastsplit"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module"] }
once_cell = "1.21.3"
simdutf = "0.6.0"
regex = "1.11.1"
fancy-regex = "0.15.0"
ahash = "0.8.12"
